---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-actions.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager-actions.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yml: |
{{ if .Values.config.pyms.overwrite }}
{{ .Values.config.pyms.content | indent 4 }}
{{ else }}
    pyms:
      services:
        metrics: true
        tracer:
          enabled: false
      config:
        debug: false
        app_name: alertmanager-actions
{{ end }}
{{- if .Values.config.alertmanager_actions }}
    alertmanager_actions:
{{ .Values.config.alertmanager_actions | indent 6 }}
{{ end }}
