---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager-actions.fullname" . }}
  labels:
{{ include "alertmanager-actions.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alertmanager-actions.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{ if .Values.preInstall.enabled }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/entrypoint.yaml") . | sha256sum }}
      {{ end }}
      labels:
        app.kubernetes.io/name: {{ include "alertmanager-actions.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: CONFIGMAP_FILE
            value: /opt/config/config.yml
          - name: ALERTMANAGER_ACTIONS_CONFIG
            value: /opt/config/config.yml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessDelay }}
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessDelay }}
            httpGet:
              path: /healthcheck
              port: http
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
        {{- if .Values.preInstall.enabled }}
          command: ["/entrypoint.sh"]
        {{- end -}}
        {{- if or .Values.preInstall.enabled .Values.secrets.enabled }}
          volumeMounts:
          {{- if .Values.secrets.enabled }}
          - name: {{ include "alertmanager-actions.fullname" . }}
            mountPath: /secrets/
            readOnly: true
          {{ end }}
          {{- if .Values.preInstall.enabled }}
          - name: entrypoint
            mountPath: /entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          {{- end }}
          - name: config
            mountPath: /opt/config/
            readOnly: true
        - image: quay.io/coreos/configmap-reload:v0.0.1
          args:
          - -webhook-url=http://localhost:8080/-/reload
          - -volume-dir=/opt/config/
          - -webhook-method=GET
          name: config-reloader
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 5m
              memory: 10Mi
          volumeMounts:
          - name: config
            mountPath: /opt/config/
            readOnly: true
        {{ end }}
      {{ if .Values.preInstall.enabled }}
      volumes:
      {{- if .Values.secrets.enabled }}
        - name: {{ include "alertmanager-actions.fullname" . }}
          secret:
            defaultMode: 420
            secretName: {{ include "alertmanager-actions.fullname" . }}
      {{ end }}
        - name: config
          configMap:
            defaultMode: 0644
            name: {{ include "alertmanager-actions.name" . }}
      {{- if .Values.preInstall.enabled }}
        - name: entrypoint
          configMap:
            defaultMode: 0777
            name: {{ include "alertmanager-actions.fullname" . }}-pre-install
      {{- end -}}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
