{{- if .Values.preInstall.value -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-actions.fullname" . }}-pre-install
  labels:
    app.kubernetes.io/name: {{ include "alertmanager-actions.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  entrypoint.sh: |
    #!/bin/sh
{{ .Values.preInstall.value | indent 4 }}
    cd /opt/code/
    uwsgi --socket /tmp/uwsgi.sock --module wsgi \
      --master --processes 4 --threads 2
{{- end -}}
