{{ if .Values.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-actions.fullname" . }}
type: Opaque
data:
  {{- range .Values.secrets.values }}
  {{ .key }}: {{ .value }}
  {{ end }}
{{ end }}
