{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "haproxy-network-ingress.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "haproxy-network-ingress.fullname" . }}
    chart: {{ include "haproxy-network-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ end -}}
